# Generated by Django 4.1.7 on 2025-06-11 15:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('recipes', '0005_comment_comment_recipes_com_created_284ea7_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='recipes_com_created_284ea7_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='recipes_com_created_8d7b28_idx'),
        ),
    ]
